#define REDIS_GIT_SHA1 "13138d9f"
#define REDIS_GIT_DIRTY "     281"
#define REDIS_BUILD_ID "Wonyongui-MacBookAir.local-1747077530"
#include "version.h"
#define REDIS_BUILD_ID_RAW SERVER_NAME VALKEY_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
